In [14]:
import utils as ut
import pandas as pd

# Validation

#### Model Type Selection + Unsmoothed LL Tuning + Benchmarks

In [29]:
static_benchmarks = pd.read_parquet(f'{ut.results_dir}/benchmarks/summary/')
ll_tuning_run = pd.read_parquet(f'{ut.results_dir}/model_selection/summary/')

# Selecting relevant columns
ll_tuning_run['model_name'] = ll_tuning_run['hurdle_model'].map({True: 'LL_hurdle', False: 'LL_NB'})
ll_tuning_run = ll_tuning_run[['w_inf', 'model_name', 'test_valid', 'non_degen_ll', 'run_timestamp']]
static_benchmarks['w_inf'] = 0

results = pd.concat([ll_tuning_run, static_benchmarks])
results.sort_values(by='non_degen_ll', ascending=False).head()

    w_inf model_name test_valid  non_degen_ll           run_timestamp
20  0.240  LL_hurdle      valid     -1.401773  20260724_175737_636570
21  0.245  LL_hurdle      valid     -1.401773  20260724_175823_795589
4   0.250  LL_hurdle      valid     -1.401800  20260724_151038_031518
19  0.235  LL_hurdle      valid     -1.401802  20260724_175651_350184
18  0.230  LL_hurdle      valid     -1.401859  20260724_175604_941838

In [28]:
# If your column is named "log_degen_ll"
results = results.reset_index(drop=True)
results.loc[results.groupby('model_name')['non_degen_ll'].idxmax()].sort_values(by='non_degen_ll', ascending=False)

    w_inf        model_name test_valid  non_degen_ll           run_timestamp
20   0.24         LL_hurdle      valid     -1.401773  20260724_175737_636570
8    0.15             LL_NB      valid     -1.431368  20260724_152051_312411
31   0.00  user_hour_hurdle      valid     -1.481319  20260724_171140_506156
30   0.00       user_hurdle      valid     -1.486078  20260724_171140_506156

#### Cluster Smoothing validaiton performance

In [15]:
cluster_smoothing = pd.read_parquet(f'{ut.results_dir}/cluster_smoothing/summary/')

In [19]:
cluster_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head(10)

,smoothed_model_name,experiment_name,sampling_seed,w_inf,cluster_param,smooth_a_mu,smooth_a_sigma2,smooth_a_p,smooth_t_mu,smooth_t_sigma2,...,hurdle_model,test_valid,non_degen_ll,non_degen_smoothed_ll,clustering_matrix_name,clustering_transformation,distance_metric,clustering_seed,cluster_inertia,run_timestamp
128,k_clusters,cluster_smoothing,6654,0.34,32,0.70,0.45,0.35,0,0,...,True,valid,-1.407317,-1.391493,u_p,log,standardised_l2,6554,1.917440e+05,20260727_163419_409125
172,k_clusters,cluster_smoothing,6654,0.32,24,0.45,0.45,0.35,0,0,...,True,valid,-1.405225,-1.391500,u_p,log,l2,6554,6.993716e+06,20260727_171056_138518
135,k_clusters,cluster_smoothing,6654,0.32,16,0.35,0.45,0.45,0,0,...,True,valid,-1.405225,-1.391791,u_p,normalise,standardised_l2,6554,5.317470e+05,20260727_163929_093527
184,k_clusters,cluster_smoothing,6654,0.30,24,0.00,0.00,0.00,120,120,...,True,valid,-1.403655,-1.392261,u_p,log,standardised_l2,6554,2.097585e+05,20260727_172112_072847
187,k_clusters,cluster_smoothing,6654,0.30,64,0.00,0.00,0.00,70,120,...,True,valid,-1.403655,-1.393039,all,normalise,standardised_l2,6554,6.950182e+05,20260727_172346_639923
146,k_clusters,cluster_smoothing,6654,0.30,24,0.35,0.25,0.15,0,0,...,True,valid,-1.403655,-1.393237,all,log,l2,6554,1.414747e+07,20260727_164844_639819
31,k_clusters,cluster_smoothing,6554,0.30,64,0.00,0.00,0.00,75,80,...,True,valid,-1.403655,-1.393268,all,normalise,standardised_l2,6554,6.950182e+05,20260724_184306_750162
175,k_clusters,cluster_smoothing,6654,0.28,16,0.00,0.00,0.00,120,90,...,True,valid,-1.402565,-1.393273,all,log,l2,6554,1.553129e+07,20260727_171324_472317
154,k_clusters,cluster_smoothing,6654,0.30,24,0.45,0.70,0.45,0,0,...,True,valid,-1.403655,-1.393381,all,log,standardised_l2,6554,3.555442e+05,20260727_165512_492109
140,k_clusters,cluster_smoothing,6654,0.34,24,0.35,0.55,0.70,0,0,...,True,valid,-1.407317,-1.393495,u_p,log,standardised_l2,6554,2.097585e+05,20260727_164320_958906

In [18]:
cluster_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).iloc[0,:]

smoothed_model_name                      k_clusters
experiment_name                   cluster_smoothing
sampling_seed                                  6654
w_inf                                          0.34
cluster_param                                    32
smooth_a_mu                                     0.7
smooth_a_sigma2                                0.45
smooth_a_p                                     0.35
smooth_t_mu                                       0
smooth_t_sigma2                                   0
smooth_t_p                                        0
linear_smooth                                  True
smoothing_target                                  1
hurdle_model                                   True
test_valid                                    valid
non_degen_ll                              -1.407317
non_degen_smoothed_ll                     -1.391493
clustering_matrix_name                          u_p
clustering_transformation                       log
distance_metric                     standardised_l2
clustering_seed                                6554
cluster_inertia                       191744.015625
run_timestamp                20260727_163419_409125
Name: 128, dtype: object

#### Global Smoothing Validation performance

In [12]:
global_smoothing = pd.read_parquet(f'{ut.results_dir}/global_smoothing/summary/')

In [ ]:
global_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head()

# Test

#### Log likelihood comparison of the best model

In [ ]:
cluster_smoothing_test = pd.read_parquet(f'{ut.results_dir}/test/cluster_smoothing/summary/')
ll_runner_test = pd.read_parquet(f'{ut.results_dir}/test/no_smoothing/summary/')

In [ ]:
pd.concat([cluster_smoothing_test, ll_runner_test]).sort_values(by='non_degen_smoothed_ll', ascending=False)