In [30]:
import utils as ut
import pandas as pd

# Validation

#### Model Type Selection + Unsmoothed LL Tuning + Benchmarks

In [29]:
static_benchmarks = pd.read_parquet(f'{ut.results_dir}/benchmarks/summary/')
ll_tuning_run = pd.read_parquet(f'{ut.results_dir}/model_selection/summary/')

# Selecting relevant columns
ll_tuning_run['model_name'] = ll_tuning_run['hurdle_model'].map({True: 'LL_hurdle', False: 'LL_NB'})
ll_tuning_run = ll_tuning_run[['w_inf', 'model_name', 'test_valid', 'non_degen_ll', 'run_timestamp']]
static_benchmarks['w_inf'] = 0

results = pd.concat([ll_tuning_run, static_benchmarks])
results.sort_values(by='non_degen_ll', ascending=False).head()

    w_inf model_name test_valid  non_degen_ll           run_timestamp
20  0.240  LL_hurdle      valid     -1.401773  20260724_175737_636570
21  0.245  LL_hurdle      valid     -1.401773  20260724_175823_795589
4   0.250  LL_hurdle      valid     -1.401800  20260724_151038_031518
19  0.235  LL_hurdle      valid     -1.401802  20260724_175651_350184
18  0.230  LL_hurdle      valid     -1.401859  20260724_175604_941838

In [28]:
# If your column is named "log_degen_ll"
results = results.reset_index(drop=True)
results.loc[results.groupby('model_name')['non_degen_ll'].idxmax()].sort_values(by='non_degen_ll', ascending=False)

    w_inf        model_name test_valid  non_degen_ll           run_timestamp
20   0.24         LL_hurdle      valid     -1.401773  20260724_175737_636570
8    0.15             LL_NB      valid     -1.431368  20260724_152051_312411
31   0.00  user_hour_hurdle      valid     -1.481319  20260724_171140_506156
30   0.00       user_hurdle      valid     -1.486078  20260724_171140_506156

#### Cluster Smoothing validaiton performance

In [47]:
cluster_smoothing = pd.read_parquet(f'{ut.results_dir}/cluster_smoothing/summary/')

In [50]:
cluster_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head()

,smoothed_model_name,experiment_name,sampling_seed,w_inf,cluster_param,smooth_a_mu,smooth_a_sigma2,smooth_a_p,smooth_t_mu,smooth_t_sigma2,...,hurdle_model,test_valid,non_degen_ll,non_degen_smoothed_ll,clustering_matrix_name,clustering_transformation,distance_metric,clustering_seed,cluster_inertia,run_timestamp
31,k_clusters,cluster_smoothing,6554,0.30,64,0.00,0.0,0.00,75,80,...,True,valid,-1.403655,-1.393268,all,normalise,standardised_l2,6554,6.950182e+05,20260724_184306_750162
11,k_clusters,cluster_smoothing,6554,0.30,16,0.00,0.0,0.00,60,70,...,True,valid,-1.403655,-1.394142,all,log,l2,6554,1.553129e+07,20260724_182527_868463
67,k_clusters,cluster_smoothing,6554,0.30,16,0.35,0.3,0.35,0,0,...,True,valid,-1.403655,-1.394648,all,none,l2,6554,7.087272e+10,20260724_191630_572678
1,k_clusters,cluster_smoothing,6554,0.25,24,0.00,0.0,0.00,25,50,...,True,valid,-1.401800,-1.395488,u_p,normalise,l2,6554,2.956195e+02,20260724_181614_674679
2,k_clusters,cluster_smoothing,6554,0.30,8,0.00,0.0,0.00,65,20,...,True,valid,-1.403655,-1.395596,u_p,log,standardised_l2,6554,3.187305e+05,20260724_181702_278460

#### Global Smoothing Validation performance

# Test

#### Log likelihood comparison of the best model

In [53]:
cluster_smoothing_test = pd.read_parquet(f'{ut.results_dir}/test/cluster_smoothing/summary/')
ll_runner_test = pd.read_parquet(f'{ut.results_dir}/test/no_smoothing/summary/')

In [ ]:
pd.concat([cluster_smoothing_test, ll_runner_test]).sort_values(by='non_degen_smoothed_ll', ascending=False)