In [3]:
import utils as ut
import pandas as pd

# Validation

#### Model Type Selection + Unsmoothed LL Tuning + Benchmarks

In [29]:
static_benchmarks = pd.read_parquet(f'{ut.results_dir}/benchmarks/summary/')
ll_tuning_run = pd.read_parquet(f'{ut.results_dir}/model_selection/summary/')

# Selecting relevant columns
ll_tuning_run['model_name'] = ll_tuning_run['hurdle_model'].map({True: 'LL_hurdle', False: 'LL_NB'})
ll_tuning_run = ll_tuning_run[['w_inf', 'model_name', 'test_valid', 'non_degen_ll', 'run_timestamp']]
static_benchmarks['w_inf'] = 0

results = pd.concat([ll_tuning_run, static_benchmarks])
results.sort_values(by='non_degen_ll', ascending=False).head()

    w_inf model_name test_valid  non_degen_ll           run_timestamp
20  0.240  LL_hurdle      valid     -1.401773  20260724_175737_636570
21  0.245  LL_hurdle      valid     -1.401773  20260724_175823_795589
4   0.250  LL_hurdle      valid     -1.401800  20260724_151038_031518
19  0.235  LL_hurdle      valid     -1.401802  20260724_175651_350184
18  0.230  LL_hurdle      valid     -1.401859  20260724_175604_941838

In [28]:
# If your column is named "log_degen_ll"
results = results.reset_index(drop=True)
results.loc[results.groupby('model_name')['non_degen_ll'].idxmax()].sort_values(by='non_degen_ll', ascending=False)

    w_inf        model_name test_valid  non_degen_ll           run_timestamp
20   0.24         LL_hurdle      valid     -1.401773  20260724_175737_636570
8    0.15             LL_NB      valid     -1.431368  20260724_152051_312411
31   0.00  user_hour_hurdle      valid     -1.481319  20260724_171140_506156
30   0.00       user_hurdle      valid     -1.486078  20260724_171140_506156

#### Cluster Smoothing validaiton performance

In [6]:
cluster_smoothing = pd.read_parquet(f'{ut.results_dir}/cluster_smoothing/nll_only/summary/')

In [11]:
cluster_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head(10)

,smoothed_model_name,experiment_name,sampling_seed,w_inf,cluster_param,smooth_a_mu,smooth_a_sigma2,smooth_a_p,smooth_t_mu,smooth_t_sigma2,...,hurdle_model,test_valid,non_degen_ll,non_degen_smoothed_ll,clustering_matrix_name,clustering_transformation,distance_metric,clustering_seed,cluster_inertia,run_timestamp
11,k_clusters,cluster_smoothing,6554,0.30,16,0.00,0.0,0.00,0.55,0.65,...,True,valid,-1.40991,-1.399535,all,log,l2,6554,1.553129e+07,20260729_194812_040881
111,k_clusters,cluster_smoothing,6554,0.30,16,0.00,0.0,0.00,0.55,0.65,...,True,valid,-1.40991,-1.399535,all,log,l2,6554,1.553129e+07,20260729_213548_007204
67,k_clusters,cluster_smoothing,6554,0.30,16,0.35,0.3,0.35,0.00,0.00,...,True,valid,-1.40991,-1.401470,all,none,l2,6554,7.087272e+10,20260729_204639_090494
167,k_clusters,cluster_smoothing,6554,0.30,16,0.35,0.3,0.35,0.00,0.00,...,True,valid,-1.40991,-1.401470,all,none,l2,6554,7.087272e+10,20260729_224054_948517
101,k_clusters,cluster_smoothing,6554,0.25,24,0.00,0.0,0.00,0.25,0.45,...,True,valid,-1.40826,-1.402085,u_p,normalise,l2,6554,2.956195e+02,20260729_212543_876903
1,k_clusters,cluster_smoothing,6554,0.25,24,0.00,0.0,0.00,0.25,0.45,...,True,valid,-1.40826,-1.402085,u_p,normalise,l2,6554,2.956195e+02,20260729_193703_339542
77,k_clusters,cluster_smoothing,6554,0.25,24,0.00,0.0,0.00,0.05,0.15,...,True,valid,-1.40826,-1.402101,all,log,l2,6554,1.414747e+07,20260729_205740_357795
177,k_clusters,cluster_smoothing,6554,0.25,24,0.00,0.0,0.00,0.05,0.15,...,True,valid,-1.40826,-1.402101,all,log,l2,6554,1.414747e+07,20260729_225238_353518
131,k_clusters,cluster_smoothing,6554,0.30,64,0.00,0.0,0.00,0.75,0.75,...,True,valid,-1.40991,-1.402379,all,normalise,standardised_l2,6554,6.950182e+05,20260729_215724_197020
31,k_clusters,cluster_smoothing,6554,0.30,64,0.00,0.0,0.00,0.75,0.75,...,True,valid,-1.40991,-1.402379,all,normalise,standardised_l2,6554,6.950182e+05,20260729_200949_956496

In [18]:
cluster_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).iloc[0,:]

smoothed_model_name                      k_clusters
experiment_name                   cluster_smoothing
sampling_seed                                  6654
w_inf                                          0.34
cluster_param                                    32
smooth_a_mu                                     0.7
smooth_a_sigma2                                0.45
smooth_a_p                                     0.35
smooth_t_mu                                       0
smooth_t_sigma2                                   0
smooth_t_p                                        0
linear_smooth                                  True
smoothing_target                                  1
hurdle_model                                   True
test_valid                                    valid
non_degen_ll                              -1.407317
non_degen_smoothed_ll                     -1.391493
clustering_matrix_name                          u_p
clustering_transformation                       log
distance_metric                     standardised_l2
clustering_seed                                6554
cluster_inertia                       191744.015625
run_timestamp                20260727_163419_409125
Name: 128, dtype: object

#### Global Smoothing Validation performance

In [12]:
global_smoothing = pd.read_parquet(f'{ut.results_dir}/global_smoothing/nll_only/summary/')

In [9]:
global_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head()

,smoothed_model_name,experiment_name,sampling_seed,w_inf,cluster_param,smooth_a_mu,smooth_a_sigma2,smooth_a_p,smooth_t_mu,smooth_t_sigma2,...,hurdle_model,test_valid,non_degen_ll,non_degen_smoothed_ll,clustering_matrix_name,clustering_transformation,distance_metric,clustering_seed,cluster_inertia,run_timestamp
63,k_clusters,global_smoothing,6554,0.25,1,0.50,0.45,0.10,0.00,0.00,...,True,valid,-1.40826,-1.402899,u,none,standardised_l2,6554,0.0,20260730_124625_460297
58,k_clusters,global_smoothing,6554,0.30,1,0.00,0.00,0.00,0.75,0.45,...,True,valid,-1.40991,-1.404200,u,none,l1,6554,0.0,20260730_124059_841352
6,k_clusters,global_smoothing,6554,0.30,1,0.60,0.45,0.65,0.00,0.00,...,True,valid,-1.40991,-1.404592,u,none,l2,6554,0.0,20260730_114627_431679
45,k_clusters,global_smoothing,6554,0.30,1,0.00,0.00,0.00,0.95,0.85,...,True,valid,-1.40991,-1.405483,u,none,standardised_l2,6554,0.0,20260730_122618_161822
1,k_clusters,global_smoothing,6554,0.25,1,0.65,0.90,0.50,0.00,0.00,...,True,valid,-1.40826,-1.406504,u,none,standardised_l2,6554,0.0,20260730_114147_698419

# Test

#### Log likelihood comparison of the best model

In [ ]:
cluster_smoothing_test = pd.read_parquet(f'{ut.results_dir}/test/cluster_smoothing/summary/')
ll_runner_test = pd.read_parquet(f'{ut.results_dir}/test/no_smoothing/summary/')

In [ ]:
pd.concat([cluster_smoothing_test, ll_runner_test]).sort_values(by='non_degen_smoothed_ll', ascending=False)