In [2]:
import utils as ut
import pandas as pd

# Validation

#### Model Type Selection + Unsmoothed LL Tuning + Benchmarks

In [29]:
static_benchmarks = pd.read_parquet(f'{ut.results_dir}/benchmarks/summary/')
ll_tuning_run = pd.read_parquet(f'{ut.results_dir}/model_selection/summary/')

# Selecting relevant columns
ll_tuning_run['model_name'] = ll_tuning_run['hurdle_model'].map({True: 'LL_hurdle', False: 'LL_NB'})
ll_tuning_run = ll_tuning_run[['w_inf', 'model_name', 'test_valid', 'non_degen_ll', 'run_timestamp']]
static_benchmarks['w_inf'] = 0

results = pd.concat([ll_tuning_run, static_benchmarks])
results.sort_values(by='non_degen_ll', ascending=False).head()

    w_inf model_name test_valid  non_degen_ll           run_timestamp
20  0.240  LL_hurdle      valid     -1.401773  20260724_175737_636570
21  0.245  LL_hurdle      valid     -1.401773  20260724_175823_795589
4   0.250  LL_hurdle      valid     -1.401800  20260724_151038_031518
19  0.235  LL_hurdle      valid     -1.401802  20260724_175651_350184
18  0.230  LL_hurdle      valid     -1.401859  20260724_175604_941838

In [28]:
# If your column is named "log_degen_ll"
results = results.reset_index(drop=True)
results.loc[results.groupby('model_name')['non_degen_ll'].idxmax()].sort_values(by='non_degen_ll', ascending=False)

    w_inf        model_name test_valid  non_degen_ll           run_timestamp
20   0.24         LL_hurdle      valid     -1.401773  20260724_175737_636570
8    0.15             LL_NB      valid     -1.431368  20260724_152051_312411
31   0.00  user_hour_hurdle      valid     -1.481319  20260724_171140_506156
30   0.00       user_hurdle      valid     -1.486078  20260724_171140_506156

#### Cluster Smoothing validaiton performance

In [6]:
cluster_smoothing = pd.read_parquet(f'{ut.results_dir}/cluster_smoothing/nll_only/summary/')

In [13]:
cluster_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head(10)

,smoothed_model_name,experiment_name,sampling_seed,w_inf,cluster_param,smooth_a_mu,smooth_a_sigma2,smooth_a_p,smooth_t_mu,smooth_t_sigma2,...,hurdle_model,test_valid,non_degen_ll,non_degen_smoothed_ll,clustering_matrix_name,clustering_transformation,distance_metric,clustering_seed,cluster_inertia,run_timestamp
307,k_clusters,cluster_smoothing,6654,0.33,30,0.7,0.55,0.4,0.0,0.0,...,True,valid,-1.412296,-1.397817,u_p,none,standardised_l2,6554,80015.273438,20260730_203536_272239
386,k_clusters,cluster_smoothing,6654,0.32,24,0.5,0.55,0.4,0.0,0.0,...,True,valid,-1.411380,-1.397861,all,none,standardised_l2,6554,121252.390625,20260730_220110_197218
385,k_clusters,cluster_smoothing,6654,0.31,30,0.6,0.60,0.3,0.0,0.0,...,True,valid,-1.410585,-1.397892,u_p,none,standardised_l2,6554,80015.273438,20260730_220005_935587
357,k_clusters,cluster_smoothing,6654,0.32,24,0.6,0.50,0.5,0.0,0.0,...,True,valid,-1.411380,-1.397893,all,none,standardised_l2,6554,121252.390625,20260730_212956_165050
330,k_clusters,cluster_smoothing,6654,0.32,32,0.5,0.50,0.5,0.0,0.0,...,True,valid,-1.411380,-1.397933,u_p,none,standardised_l2,6554,77954.406250,20260730_210037_124869
339,k_clusters,cluster_smoothing,6654,0.33,26,0.6,0.60,0.6,0.0,0.0,...,True,valid,-1.412296,-1.397982,all,none,standardised_l2,6554,112586.375000,20260730_211023_742747
310,k_clusters,cluster_smoothing,6654,0.32,28,0.6,0.55,0.5,0.0,0.0,...,True,valid,-1.411380,-1.397985,all,none,standardised_l2,6554,107635.953125,20260730_203853_886779
305,k_clusters,cluster_smoothing,6654,0.31,32,0.5,0.55,0.5,0.0,0.0,...,True,valid,-1.410585,-1.398030,u_p,none,standardised_l2,6554,77954.406250,20260730_203319_259385
321,k_clusters,cluster_smoothing,6654,0.31,26,0.7,0.60,0.5,0.0,0.0,...,True,valid,-1.410585,-1.398081,u_p,none,standardised_l2,6554,87277.500000,20260730_205053_023171
398,k_clusters,cluster_smoothing,6654,0.31,28,0.7,0.60,0.5,0.0,0.0,...,True,valid,-1.410585,-1.398089,u_p,none,standardised_l2,6554,82832.218750,20260730_221404_042971

#### Global Smoothing Validation performance

In [3]:
global_smoothing = pd.read_parquet(f'{ut.results_dir}/global_smoothing/nll_only/summary/')

In [4]:
global_smoothing.sort_values(by='non_degen_smoothed_ll', ascending=False).head()

,smoothed_model_name,experiment_name,sampling_seed,w_inf,cluster_param,smooth_a_mu,smooth_a_sigma2,smooth_a_p,smooth_t_mu,smooth_t_sigma2,...,hurdle_model,test_valid,non_degen_ll,non_degen_smoothed_ll,clustering_matrix_name,clustering_transformation,distance_metric,clustering_seed,cluster_inertia,run_timestamp
235,k_clusters,global_smoothing,6654,0.33,1,0.55,0.55,0.25,0.0,0.0,...,True,valid,-1.412296,-1.400743,u,none,l2,6554,0.0,20260730_235309_885521
298,k_clusters,global_smoothing,6654,0.32,1,0.45,0.55,0.30,0.0,0.0,...,True,valid,-1.411380,-1.400866,u,none,l2,6554,0.0,20260731_005217_555315
241,k_clusters,global_smoothing,6654,0.33,1,0.45,0.55,0.25,0.0,0.0,...,True,valid,-1.412296,-1.400873,u,none,l2,6554,0.0,20260730_235853_539463
280,k_clusters,global_smoothing,6654,0.34,1,0.50,0.50,0.35,0.0,0.0,...,True,valid,-1.413337,-1.400883,u,none,l2,6554,0.0,20260731_003536_097128
244,k_clusters,global_smoothing,6654,0.33,1,0.55,0.45,0.25,0.0,0.0,...,True,valid,-1.412296,-1.400909,u,none,l2,6554,0.0,20260731_000144_953936

# Test

#### Log likelihood comparison of the best model

In [8]:
cluster_smoothing_test = pd.read_parquet(f'{ut.results_dir}/test/cluster_smoothing/full/summary/')
ll_runner_test = pd.read_parquet(f'{ut.results_dir}/test/no_smoothing/full/summary/')
global_smoothing_test = pd.read_parquet(f'{ut.results_dir}/test/global_smoothing/full/summary/')

In [ ]:
pd.concat([cluster_smoothing_test, ll_runner_test]).sort_values(by='non_degen_smoothed_ll', ascending=False)

In [22]:
cluster_smoothing_test[cluster_smoothing_test['breakdown_type'] == 'overall']['non_degen_ll_sum'] / cluster_smoothing_test[cluster_smoothing_test['breakdown_type'] == 'overall']['n_bins_scored']

0   -1.370316
dtype: float64

In [9]:
global_smoothing_test[global_smoothing_test['breakdown_type'] == 'overall']['non_degen_ll_sum'] / global_smoothing_test[global_smoothing_test['breakdown_type'] == 'overall']['n_bins_scored']

0   -1.371676
dtype: float64

In [31]:
ll_runner_test[ll_runner_test['breakdown_type'] == 'overall']['non_degen_ll_sum'] / ll_runner_test[ll_runner_test['breakdown_type'] == 'overall']['n_bins_scored']

0   -1.376381
dtype: float64

In [30]:
benchmarks_test = pd.read_parquet(f'{ut.results_dir}/benchmarks/full/summary/')
benchmarks_test[benchmarks_test['breakdown_type'] == 'overall']['non_degen_ll_sum'] / benchmarks_test[benchmarks_test['breakdown_type'] == 'overall']['n_bins_scored']

0    -1.460846
23   -1.452264
dtype: float64

In [12]:
global_smoothing_test['breakdown_type']

0             overall
1     activity_decile
2     activity_decile
3     activity_decile
4     activity_decile
5     activity_decile
6     activity_decile
7     activity_decile
8     activity_decile
9     activity_decile
10    activity_decile
11    distance_decile
12    distance_decile
13    distance_decile
14    distance_decile
15    distance_decile
16    distance_decile
17    distance_decile
18    distance_decile
19    distance_decile
20    distance_decile
21          user_type
22          user_type
Name: breakdown_type, dtype: object