In [1]:
import polars as pl

In [2]:
df = pl.scan_parquet('/home/ma/a/alb25/Project/thesis_code/data/raw')

In [ ]:
# time	source_user@domain	destination_user@domain	source_computer	destination_computer	authentication_type	logon_type	authentication_orientation	success/failure
df.head().collect()

shape: (5, 9)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ time ┆ source_use ┆ destinatio ┆ source_com ┆ … ┆ authentica ┆ logon_typ ┆ authentic ┆ success/f │
│ ---  ┆ r@domain   ┆ n_user@dom ┆ puter      ┆   ┆ tion_type  ┆ e         ┆ ation_ori ┆ ailure    │
│ str  ┆ ---        ┆ ain        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ entation  ┆ ---       │
│      ┆ str        ┆ ---        ┆ str        ┆   ┆ str        ┆ str       ┆ ---       ┆ str       │
│      ┆            ┆ str        ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C1250      ┆ … ┆ NTLM       ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C586       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C101$@DOM1 ┆ C101$@DOM1 ┆ C988       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│ 1    ┆ C1020$@DOM ┆ SYSTEM@C10 ┆ C1020      ┆ … ┆ Negotiate  ┆ Service   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 20         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C1021$@DOM ┆ C1021$@DOM ┆ C1021      ┆ … ┆ Kerberos   ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 1          ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [3]:
# Number of rows: 1051430459
df.select(pl.col('time').len()).collect()

shape: (1, 1)
┌────────────┐
│ time       │
│ ---        │
│ u32        │
╞════════════╡
│ 1051430459 │
└────────────┘

In [3]:
source_users = df.select(pl.col('source_user@domain').unique()).collect()

In [4]:
destination_users = df.select(pl.col('destination_user@domain').unique()).collect()

In [ ]:
# 99968 users
pl.concat([source_users.select(pl.col('source_user@domain').alias('user')), destination_users.select(pl.col('destination_user@domain').alias('user'))]).unique().select(pl.len())

shape: (1, 1)
┌───────┐
│ len   │
│ ---   │
│ u32   │
╞═══════╡
│ 99968 │
└───────┘

In [ ]:
df = df.with_columns(pl.when(pl.col('source_user@domain').str.contains(r'^U\d+@')).then(pl.lit('human'))
          .when(pl.col('source_user@domain').str.contains(r'^C\d+\$@')).then(pl.lit('machine'))
          .when(pl.col('source_user@domain').str.contains(r'^(SYSTEM|LOCAL SERVICE|NETWORK SERVICE)@')).then(pl.lit('system'))
          .when(pl.col('source_user@domain').str.contains(r'^ANONYMOUS LOGON@')).then(pl.lit('anon'))
          .otherwise(pl.lit('other'))
          .alias('source_user_type'))

In [ ]:
df.group_by('source_user_type').len().collect()